[manifest]
version = "1.2"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = "dummypatch.lua"
pattern = '''asdasdasd'''
position = "at"
payload = '''asdasdad'''
match_indent = true